backend:
  name: github
  repo: amykapernick/amygoestoperth
  branch: netlifycms

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Publish Date", name: "publish-date", widget: "date"}
      - {label: "Update Date", name: "update-date", widget: "date"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Image", name: "featured-image", widget: "image"}
      - label: "Body" 
        name: "body"
        widget: "list"
        fields:
          - {label: "Content", name: "content", widget: "markdown"}
          - {label: "Image", name: "image", widget: "image"}
          - label: "Embed"
            name: "embed" 
            widget: "string"
            field:
              label: "Embed Type"
              name: "embed-type" 
              widget: "select"
              options:
                - {label: "Twitter", value: "twitter"}
                - {label: "Codepen", value: "codepen"}
                - {label: "Instagram", value: "instagram"}      