backend:
  name: github
  repo: amykapernick/amygoestoperth

media_folder: static/img
public_folder: img

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: publish_date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }