backend:
  name: github
  repo: amykapernick/amygoestoperth
  branch: netlify-gatsby

media_folder: static/img
public_folder: /img

collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    editor:
      preview: false
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - { name: path, label: Path, widget: string}
      - { name: title, label: Title }
      - { name: publishDate, label: "Publish Date", widget: date }
      - { name: updateDate, label: "Update Date", widget: date }
      - { name: description, label: "Meta Description", widget: text }
      - { name: tags, label: Tags, widget: list }
      - { name: body, label: Body, widget: markdown}