backend:
  name: git-gateway

media_folder: static/img # Media files will be stored in the repo under static/images/uploads
public_folder: /img # The src attribute for uploaded media will begin with /images/uploads
display_url: https://amygoestoperth.com.au
slug:
  encoding: "ascii"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Publish Date", name: "publish-date", widget: "date"}
      - {label: "Update Date", name: "update-date", widget: "date"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Image", name: "featured-image", widget: "image", required: false}
      - label: "Body" 
        name: "body"
        widget: "list"
        fields:
          - {label: "Content", name: "content", widget: "markdown"}
          - {label: "Image", name: "image", widget: "image"}
          - label: "Embed"
            name: "embed" 
            widget: "string"
            field:
              label: "Embed Type"
              name: "embed-type" 
              widget: "select"
              options:
                - {label: "Twitter", value: "twitter"}
                - {label: "Codepen", value: "codepen"}
                - {label: "Instagram", value: "instagram"}      
    editor:
      preview: false