backend:
  name: github
  repo: amykapernick/amygoestoperth
  branch: netlify-gatsby

media_folder: static/img
public_folder: /img

collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    editor:
      preview: false
    fields:
      - { name: path, label: Path }
      - { name: publishDate, label: Date, widget: date }
      - { name: title, label: Title }
      - name: body
        label: Body
        widget: list
        fields:
          - {name: content, label: content, widget: markdown}