backend:
  name: github
  repo: amykapernick/amygoestoperth
  branch: netlify-gatsby

media_folder: static/img
public_folder: /img

collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    editor:
      preview: false
    fields:
      - { name: path, label: Path, widget: string}
      - { name: publishDate, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown}
      - name: bodyContent
        label: "Body Content"
        widget: list
        fields: 
          - { name: content, label: Content, widget: markdown }
          - { name: embed, label: "Embed Content", widget: string }